
title: Hendricks Website
email: meine-Email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Die beste Website im ganzen Internet!!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: onylwice1
github_username:  onlywice1

# Build settings
markdown: kramdown
