remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one# Site settings
title: Hendricks Website
email: meine-Email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Die beste Website im ganzen Internet!!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: onylwice1
github_username:  onlywice1

# Build settings
markdown: kramdown
